"""add board invite links

Revision ID: 3833bb05a57c
Revises: 0b805a777127
Create Date: 2026-08-20 12:28:59.072711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3833bb05a57c'
down_revision: Union[str, None] = '0b805a777127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_invite_links',
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('fk_board_invite_links_board_id_boards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_board_invite_links_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_board_invite_links'))
    )
    op.create_index(op.f('ix_board_invite_links_board_id'), 'board_invite_links', ['board_id'], unique=False)
    op.create_index(op.f('ix_board_invite_links_token'), 'board_invite_links', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_board_invite_links_token'), table_name='board_invite_links')
    op.drop_index(op.f('ix_board_invite_links_board_id'), table_name='board_invite_links')
    op.drop_table('board_invite_links')
    # ### end Alembic commands ###
