"""add list color, board star, inbox items

Revision ID: 5118e8fbf5a9
Revises: 5aab07738383
Create Date: 2026-08-20 08:13:42.840686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5118e8fbf5a9'
down_revision: Union[str, None] = '5aab07738383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox_items',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_inbox_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inbox_items'))
    )
    op.create_index(op.f('ix_inbox_items_user_id'), 'inbox_items', ['user_id'], unique=False)
    op.add_column('board_members', sa.Column('is_starred', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('lists', sa.Column('color', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lists', 'color')
    op.drop_column('board_members', 'is_starred')
    op.drop_index(op.f('ix_inbox_items_user_id'), table_name='inbox_items')
    op.drop_table('inbox_items')
    # ### end Alembic commands ###
