"""initial schema

Revision ID: 5aab07738383
Revises: 
Create Date: 2026-08-19 19:21:07.226326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5aab07738383'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_workspaces_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_table('boards',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('background', sa.String(length=255), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_template', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_boards_created_by_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_boards_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boards'))
    )
    op.create_index('ix_boards_workspace_id_is_archived', 'boards', ['workspace_id', 'is_archived'], unique=False)
    op.create_table('templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("scope IN ('board', 'card')", name=op.f('ck_templates_ck_templates_scope')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_templates_created_by_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_templates_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates'))
    )
    op.create_index(op.f('ix_templates_workspace_id'), 'templates', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', name='workspace_role'), server_default='member', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_members_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_members_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_members')),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_members_workspace_id_user_id')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('automation_rules',
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('trigger_type', sa.String(length=100), nullable=False),
    sa.Column('trigger_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('fk_automation_rules_board_id_boards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_automation_rules_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_rules'))
    )
    op.create_index('ix_automation_rules_board_id_is_enabled', 'automation_rules', ['board_id', 'is_enabled'], unique=False)
    op.create_index('ix_automation_rules_board_id_trigger_type', 'automation_rules', ['board_id', 'trigger_type'], unique=False)
    op.create_table('board_members',
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', 'viewer', name='board_role'), server_default='member', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('fk_board_members_board_id_boards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_board_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_board_members')),
    sa.UniqueConstraint('board_id', 'user_id', name='uq_board_members_board_id_user_id')
    )
    op.create_index(op.f('ix_board_members_board_id'), 'board_members', ['board_id'], unique=False)
    op.create_index(op.f('ix_board_members_user_id'), 'board_members', ['user_id'], unique=False)
    op.create_table('custom_fields',
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.Enum('text', 'number', 'dropdown', 'checkbox', 'date', name='custom_field_type'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('fk_custom_fields_board_id_boards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_fields'))
    )
    op.create_index('ix_custom_fields_board_id_position', 'custom_fields', ['board_id', 'position'], unique=False)
    op.create_table('labels',
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), server_default='', nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('fk_labels_board_id_boards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labels')),
    sa.UniqueConstraint('board_id', 'name', 'color', name='uq_labels_board_id_name_color')
    )
    op.create_table('lists',
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('fk_lists_board_id_boards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lists'))
    )
    op.create_index('ix_lists_board_id_position', 'lists', ['board_id', 'position'], unique=False)
    op.create_table('automation_actions',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('action_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['automation_rules.id'], name=op.f('fk_automation_actions_rule_id_automation_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_actions'))
    )
    op.create_index('ix_automation_actions_rule_id_position', 'automation_actions', ['rule_id', 'position'], unique=False)
    op.create_table('cards',
    sa.Column('list_id', sa.UUID(), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('due_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('due_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('cover_attachment_id', sa.UUID(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('fk_cards_board_id_boards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_cards_created_by_users')),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], name=op.f('fk_cards_list_id_lists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cards'))
    )
    op.create_index('ix_cards_board_id_due_date', 'cards', ['board_id', 'due_date'], unique=False, postgresql_where=sa.text('due_date IS NOT NULL'))
    op.create_index('ix_cards_board_id_is_archived', 'cards', ['board_id', 'is_archived'], unique=False)
    op.create_index('ix_cards_list_id_position', 'cards', ['list_id', 'position'], unique=False)
    op.create_table('activity_log',
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('automation_rule_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_activity_log_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['automation_rule_id'], ['automation_rules.id'], name=op.f('fk_activity_log_automation_rule_id_automation_rules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('fk_activity_log_board_id_boards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_activity_log_card_id_cards'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_log'))
    )
    op.create_index('ix_activity_log_board_id_created_at', 'activity_log', ['board_id', 'created_at'], unique=False)
    op.create_index('ix_activity_log_card_id_created_at', 'activity_log', ['card_id', 'created_at'], unique=False)
    op.create_table('attachments',
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_attachments_card_id_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_attachments_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    op.create_index(op.f('ix_attachments_card_id'), 'attachments', ['card_id'], unique=False)
    # Deferred: cards.cover_attachment_id <-> attachments is a genuine circular FK,
    # so it's added only now that both tables exist.
    op.create_foreign_key(
        'fk_cards_cover_attachment_id', 'cards', 'attachments', ['cover_attachment_id'], ['id'], ondelete='SET NULL'
    )
    op.create_table('card_labels',
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('label_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_card_labels_card_id_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], name=op.f('fk_card_labels_label_id_labels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id', 'label_id', name=op.f('pk_card_labels'))
    )
    op.create_index('ix_card_labels_label_id', 'card_labels', ['label_id'], unique=False)
    op.create_table('card_members',
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_card_members_card_id_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_card_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id', 'user_id', name=op.f('pk_card_members'))
    )
    op.create_index(op.f('ix_card_members_user_id'), 'card_members', ['user_id'], unique=False)
    op.create_table('checklists',
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), server_default='Checklist', nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_checklists_card_id_cards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklists'))
    )
    op.create_index('ix_checklists_card_id_position', 'checklists', ['card_id', 'position'], unique=False)
    op.create_table('comments',
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_comments_author_id_users')),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_comments_card_id_cards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index('ix_comments_card_id_created_at', 'comments', ['card_id', 'created_at'], unique=False)
    op.create_table('custom_field_values',
    sa.Column('custom_field_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_custom_field_values_card_id_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_fields.id'], name=op.f('fk_custom_field_values_custom_field_id_custom_fields'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_field_values')),
    sa.UniqueConstraint('custom_field_id', 'card_id', name='uq_custom_field_values_custom_field_id_card_id')
    )
    op.create_index(op.f('ix_custom_field_values_card_id'), 'custom_field_values', ['card_id'], unique=False)
    op.create_table('checklist_items',
    sa.Column('checklist_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=1024), nullable=False),
    sa.Column('is_complete', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_checklist_items_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], name=op.f('fk_checklist_items_checklist_id_checklists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklist_items'))
    )
    op.create_index('ix_checklist_items_checklist_id_position', 'checklist_items', ['checklist_id', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_checklist_items_checklist_id_position', table_name='checklist_items')
    op.drop_table('checklist_items')
    op.drop_index(op.f('ix_custom_field_values_card_id'), table_name='custom_field_values')
    op.drop_table('custom_field_values')
    op.drop_index('ix_comments_card_id_created_at', table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_checklists_card_id_position', table_name='checklists')
    op.drop_table('checklists')
    op.drop_index(op.f('ix_card_members_user_id'), table_name='card_members')
    op.drop_table('card_members')
    op.drop_index('ix_card_labels_label_id', table_name='card_labels')
    op.drop_table('card_labels')
    op.drop_constraint('fk_cards_cover_attachment_id', 'cards', type_='foreignkey')
    op.drop_index(op.f('ix_attachments_card_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index('ix_activity_log_card_id_created_at', table_name='activity_log')
    op.drop_index('ix_activity_log_board_id_created_at', table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_index('ix_cards_list_id_position', table_name='cards')
    op.drop_index('ix_cards_board_id_is_archived', table_name='cards')
    op.drop_index('ix_cards_board_id_due_date', table_name='cards', postgresql_where=sa.text('due_date IS NOT NULL'))
    op.drop_table('cards')
    op.drop_index('ix_automation_actions_rule_id_position', table_name='automation_actions')
    op.drop_table('automation_actions')
    op.drop_index('ix_lists_board_id_position', table_name='lists')
    op.drop_table('lists')
    op.drop_table('labels')
    op.drop_index('ix_custom_fields_board_id_position', table_name='custom_fields')
    op.drop_table('custom_fields')
    op.drop_index(op.f('ix_board_members_user_id'), table_name='board_members')
    op.drop_index(op.f('ix_board_members_board_id'), table_name='board_members')
    op.drop_table('board_members')
    op.drop_index('ix_automation_rules_board_id_trigger_type', table_name='automation_rules')
    op.drop_index('ix_automation_rules_board_id_is_enabled', table_name='automation_rules')
    op.drop_table('automation_rules')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_templates_workspace_id'), table_name='templates')
    op.drop_table('templates')
    op.drop_index('ix_boards_workspace_id_is_archived', table_name='boards')
    op.drop_table('boards')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
